apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: tasks
  name: tasks
spec:
  replicas: 2
  selector:
    matchLabels:
      name: tasks
  template:
    metadata:
      labels:
        name: tasks
    spec:
      containers:
      - image: quay.io/cmedeiro/tasks-app:latest
        name: tasks
        ports:
        - containerPort: 8080
          name: http-server
