apiVersion: 'image.openshift.io/v1'
kind: ImageStream
metadata:
  labels:
    name: tasks
  name: tasks
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'latest'
      from:
        kind: DockerImage
        name: quay.io/cmedeiro/tasks-app:latest
