---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: tasks
  namespace: tasks
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - tasks
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
