apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: tasks-placement
  namespace: tasks
  labels:
    app: tasks
spec:
  clusterSelector:
    matchLabels: 
      vendor: OpenShift
