---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mapit
  namespace: mapit
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mapit
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
